### ISSUE TITLE
Wrong exit code

### ISSUE THREAD

**Issue by codingjoe** [mtuchowski/mdspell#3]
Hi,

I might just do something wrong, but travis doesn't fail on translation errors.

https://travis-ci.org/codingjoe/django-cc/jobs/122596051

The funny thing is, when I run the same command locally it works:
```shell
mdspell --en-us -ran "**/*.md"; echo $?
    howto/travis-ci.md
        4 | with Github. 
        9 | Travis-CI is free for OpenSource projects. We encourage you to 
       11 | OpenSource packages you rely on every da 
       20 | Next head over to [travis-ci.org](https://travis-ci.org/)  
       23 | If you have the [travis command line tool] installed  
       28 | ## Automatic PyPi deployment 
       31 | [PyPi deployment](https://docs.trav 
       34 | [travis command line tool] 
       43 | Type in your PyPi username and password and ans 
       46 | ew deployment section in your travis 
       47 | config. Similar to this: 
       65 | Github. 
       71 | Travis-CI will now do the PyPi deployment for you! 

    README.md
      114 | ### pydocstyle 
      116 | [pydocstyle][pydocstyle] checks doc strin 

>> 15 spelling errors found in 3 files
1
```

**Comment by mtuchowski** [comment]
Looking into that (looks like I forgot about `exitcode`).

**Comment by codingjoe** [comment]
Thank :)

**Comment by mtuchowski** [comment]
@codingjoe Fixed and released in version `0.1.8`. Please test if it works for you and give notify me so I can close the issue.

**Comment by mtuchowski** [comment]
@codingjoe Hey, I just noticed: Your project uses `node-markdown-spellcheck` that is not this project (this one is Ruby). Your were looking for https://github.com/lukeapage/node-markdown-spellcheck ;)

Anyway, this project had the same problem. So, thank for reporting it, I guess...

**Comment by codingjoe** [comment]
@mtuchowski oooh, how embarrassing :/
